### ISSUE TITLE
Integration suite rot: 7 pre-existing failures exposed after fixing the skipped-fixture path

### ISSUE THREAD

**Issue by anton-tvrz** [anton-tvrz/project-network-synapse-quattro#205]
## Background

`tests/integration/conftest.py` and `test_schema_loading.py` pointed at `backend/network_synapse/scripts/load_schemas.py`, a path that has not existed since the loader moved to `schemas/`. The fixture called `pytest.skip` on the missing file, so **all 31 integration tests silently skipped** — the "Integration Tests (Infrahub)" job has been green without executing anything. Fixed in #204.

With the suite actually running (20 pass, 4 skip), 7 pre-existing failures are now visible. None are caused by #204; all predate it and were simply invisible.

## Failures

**Infrahub resource-pool API drift** — `GraphQL errors: 'node'` from `resource_manager._graphql`:
- `test_resource_pools.py::TestPoolCreation::test_create_number_pool`
- `test_resource_pools.py::TestPoolCreation::test_create_number_pool_idempotent`
- `test_resource_pools.py::TestNumberAllocation::test_allocate_number_returns_value`
- `test_resource_pools.py::TestNumberAllocation::test_sequential_allocations_are_unique`

**Client return-type drift** — `list_devices()` returns strings, but the test expects objects with `.name`:
- `test_seed_data.py::TestSeedDataPopulation::test_devices_created` (`AttributeError: 'str' object has no attribute 'name'`)

**Require a deployed containerlab topology** — may be environment-dependent rather than broken:
- `test_placeholder.py::test_containerlab_gnmi_connectivity`
- `test_placeholder.py::test_containerlab_bgp_state`

## Also skipping

`test_transforms.py` (4 tests) skips on `Cannot query field 'InfrahubTransformPython' on type 'Query'. Did you mean 'CoreTransformPython'?` — an Infrahub API rename the transform helper has not caught up with.

## Why this matters beyond the failures

The job is `continue-on-error: true`, so integration failures never block the quality gate. Combined with a fixture that skips silently when its path is wrong, the suite could rot indefinitely without a signal. Worth deciding whether the missing-script `pytest.skip` should become a hard failure, so a broken fixture path can never masquerade as a pass again.

**Comment by anton-tvrz** [comment]
## Additional finding: checks crash on a detached HEAD

Surfaced while fixing #204's integration tests, and it affects every check in `backend/network_synapse/checks/`, not just the new one.

`InfrahubCheck._write_log_entry` builds each log line with `self.branch_name`. When no branch was passed to the constructor, that property asks git for the active branch:

```python
# infrahub_sdk/checks.py:143
self.branch = str(self.git.active_branch)
# -> dulwich/porcelain/__init__.py:3945
active_ref = r.refs.follow(HEADREF)[0][1]   # IndexError on detached HEAD
```

GitHub Actions checks out pull requests in a detached HEAD state, so **any check that logs raises `IndexError: list index out of range`** there. Verified locally with `git checkout --detach`:

```
BGPSessionCheck:     IndexError: list index out of range
OrphanedRulesCheck:  IndexError: list index out of range
```

#204 works around it in its own tests by constructing the check with `branch="main"` — the SDK's own escape hatch, since `branch_name` returns the supplied value without touching git. Infrahub passes the branch when it runs checks for real, so this is a test-environment problem rather than a production one.

Two things worth doing beyond that workaround:

1. `tests/unit/test_checks.py` constructs `BGPSessionCheck()`, `IPUniquenessCheck()`, and `InterfaceConsistencyCheck()` with no branch. They pass today, including under a detached HEAD when run through pytest — but they fail outside pytest under the same HEAD state, so the immunity is incidental and not something to rely on. Giving them an explicit branch would make them deterministic.
2. Worth deciding whether the project's checks should set a branch default themselves rather than every caller remembering.
